FROM alpine:3.10.1

#RUN useradd -U -m -d /home/azcopy azcopy

# update the packages and install wget
RUN apk add wget

# copy & install azcopy binary | delete the downlaoded archive
RUN wget -O azcopyv10.tar https://azcopyvnext.azureedge.net/release20190703/azcopy_linux_amd64_10.2.1.tar.gz --no-check-certificate \
    && tar x -f azcopyv10.tar --strip-components=1  \
#   && chown azcopy:azcopy azcopy \
    && rm azcopyv10.tar

#USER azcopy

# RUN curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash--no-check-certificatels -l